apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cdit-cluster
  region: us-west-2
  version: "1.27"

nodeGroups:
  - name: ng-1
    instanceType: t2.medium
    desiredCapacity: 4
    volumeSize: 10
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
  - name: ng-2
    instanceType: t2.medium
    desiredCapacity: 4
    volumeSize: 10
    ssh:
      publicKeyPath: ~/.ssh/id_rsa.pub



